export const MISSIONS = [
  'Take three slow, deep breaths right now.',
  'Send one kind message to someone.',
  'Drink a full glass of water.',
  'Step outside for two minutes and notice the air.',
  'Write down one thing you’re grateful for.',
  'Stretch your body for one minute.',
  'Compliment yourself out loud.',
  'Clean one small space around you.',
  'Smile at your reflection.',
  'Do one task you’ve been postponing — just start it.',
  'Put your phone away for five quiet minutes.',
  'Listen to one song that lifts your mood.',
  'Forgive yourself for something small.',
  'Organize one tiny thing (a drawer, a bag, your notes).',
  'Sit in silence for one full minute.',
  'Send a message you’ve been afraid to send.',
  'Take a short walk, even inside your room.',
  'Write down one fear — then tear the paper.',
  'Drink something warm slowly.',
  'Say “no” to something you don’t want to do.',
  'Do one brave thing today — even if it’s small.',
  'Wear something that makes you feel confident.',
  'Look at the sky for 30 seconds.',
  'Give yourself permission to rest.',
  'Start something imperfectly.',
  'Hug someone — or hug yourself.',
  'Write one sentence about how you truly feel.',
  'Declutter five items.',
  'Do something playful for two minutes.',
  'End your day by thanking yourself.',
];
